version: '3'
services:
  graph_db:
    image: neo4j
    container_name: "chh-core-graphdb-container"
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./sampleData/db/dbms:/data/dbms
    healthcheck:
      test: "exit 0"

  core_api:
    build: api/.
    container_name: "chh-core-api-container"
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/app
    depends_on:
      graph_db:
        condition: service_healthy
  
  core_web:
    build: web_app/.
    container_name: "chh-core-web-container"
    ports:
      - "5000:5000"
    depends_on:
      core_api:
        condition: service_started